### ISSUE TITLE
[Copy Attachment To Clipboard] Is it still a thing?

### ISSUE THREAD

**Issue by mirh** [RealRaven2000/SmartTemplate4#1]
Hi. 
I'm sorry if this is really the most unorthodox possible way to ask you, but I was wondering if you just so happened to have access to this extension or its source code. 

Thanks.

**Comment by MarkyMarkDE** [comment]
SmartTemplate<sup>4</sup> is our Addon, sure we have access to it's source Code.
Please contact us over following page: http://smarttemplate4.mozdev.org/#contact

**Comment by mirh** [comment]
I was asking Axel(?) for some elucidation on an older deprecated extension of his..

**Comment by RealRaven2000** [comment]
Dear Mirh,

and I hope you got my answer?

> *To:* Mirh -
> *From: *Axel Grude
> *Sent: *Friday, 10/12/2018 20:34 GMT DT +0100 [Week 41]
> *Subject:* Re: [RealRaven2000/SmartTemplate4] [Copy Attachment To Clipboard] Is it 
> still a thing? (#1)
>
> Dear Mirh,
>
> I have the source code of the ADd-on. The problem is I do not have the source code 
> of the external Windows-Programm (binary) that copies the file to the clipboard 
> externally. And without this, I won't be able to fix it or release a version on 
> addons.thunderbird.net. Were you interested in fixing it?

Axel

*Axel Grude <mailto:axel.grude@gmail.com>*
Music Production and Composition
Thunderbird Add-ons Developer (QuickFolders 
<https://addons.mozilla.org/thunderbird/addon/quickfolders-tabbed-folders/>, 
quickFilters <https://addons.mozilla.org/thunderbird/addon/quickfilters/>, 
QuickPasswords <https://addons.mozilla.org/firefox/addon/quickpasswords/>, Zombie Keys 
<https://addons.mozilla.org/thunderbird/addon/zombie-keys/>, SmartTemplate4 
<https://addons.mozilla.org/thunderbird/addon/smarttemplate4/>)
Visit my YouTube Channel <https://www.youtube.com/c/thunderbirddaily> for email 
productivity tips Get Thunderbird!
