### ISSUE TITLE
File Attachment Function for SmartTemplates

### ISSUE THREAD

**Issue by dma2386** [RealRaven2000/SmartTemplate4#101]
I'd like to suggest a %attach()% function for Smartemplate4.

One could just then just include that into a File template to attach whatever documents are needed for the purpose.

Very useful when one wants to send a standard reply which has an identical pdf attached to multiple emails.

It would be more convenient to pre-load the reply with the pdf already attached, rather than having to attach it to each reply.

**Comment by RealRaven2000** [comment]
Actually, this already exists - 

- expand the settings dialog
- click on variables tab and expand the "fixed variables" section
- click on the %attach% button - this will prompt for a file and put the proper syntax to the currently edited template text box at cursor position:
![image](https://user-images.githubusercontent.com/6314674/102638594-ab793000-414f-11eb-9abb-4f0df81818af.png)

(file url will be correct depending on your OS)

**Comment by RealRaven2000** [comment]
closing as resolved (as it already exists) - onwards and upwards...
