### ISSUE TITLE
Duplicate template syndrome #108 still exists

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/SmartTemplate4#111]
Version 3.3 clearly improves duplicate template syndrome #108  but still some mails are affected... let me know if their EML contents, or other data can be useful.

**Comment by RealRaven2000** [comment]
... or you could just have reopened #108 ?

**Comment by macdeport** [comment]
> ... or you could just have reopened https://github.com/RealRaven2000/SmartTemplate4/issues/108 ?

But, sorry, I don't know how

**Comment by RealRaven2000** [comment]
> > ... or you could just have reopened #108 ?
> 
> But, sorry, I don't know how

You may have had trouble finding the old one? you can filter at the top for closed issues by clicking that checkbox:

![image](https://user-images.githubusercontent.com/6314674/103560844-6c1d4400-4eb0-11eb-848c-90491eb5265f.png)

and yes you can add comments to closed issues, I will still get notified about them. Closing this one!
