### ISSUE TITLE
Feature Request: Insert clipboard contents....

### ISSUE THREAD

**Issue by pitm2000** [RealRaven2000/SmartTemplate4#118]
Die Zwischenablage von Windows einfügen

z.B. mit %%ZWISCHENABLAGE%%

ist das lösbar ??

mfg

**Comment by RealRaven2000** [comment]
> Die Zwischenablage von Windows einfügen
> z.B. mit %%ZWISCHENABLAGE%% 
> ist das lösbar ??

ja wäre im Prinzip machbar (nicht nur für Windows). Vielleicht als `%clipboard.get%`, mal sehen. Ich könnte mir auch Erweiterungen für `%header.set%` welche die Zwischenablage unterstützen als brauchbar vorstellen.

Clipboard support would be generally possible (not just in Windows). Maybe in the form of  `%clipboard.get%`, we will see. It could also be useful to extend  `%header.set%` and friends with clipboard support.

**Comment by pitm2000** [comment]
Hoffentlich ist das machbar...

thx

**Comment by RealRaven2000** [comment]
Try this version and use %clipboard% - if you paste into a HTML mail, this will be interpreted as HTML (so you could copy a string like `<b>fett</b>` )

[smartTemplate-fx-3.7pre27.zip](https://github.com/RealRaven2000/SmartTemplate4/files/7001650/smartTemplate-fx-3.7pre27.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
Added support or pasting HTML - now you can insert a little formatted text from  a Word document or a webpage. Note: this may fail if you paste into a plain text mail, need to check the behavior there.

[smartTemplate-fx-3.7pre35.zip](https://github.com/RealRaven2000/SmartTemplate4/files/7002308/smartTemplate-fx-3.7pre35.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
Implemented in  3.7, published on 20/08/2021

**Comment by RealRaven2000** [comment]
Can you test the new version in issue #210 please?

There were issues with using (copying to) clipboard multiple times, so there is a new version I plan to release. So far I have tested the preview version with  `%header.set(..,toclipboard)%` and `%matchTextFromSubject(...,toclipboard)%`.
