### ISSUE TITLE
XML Parsing Error settings dialog (it / sv / uk locales)

### ISSUE THREAD

**Issue by matteotrubini** [RealRaven2000/SmartTemplate4#119]
Trying to open settings:

TB: 78.7.1 (tested on 32/64 bit) - Locale "it"
ST: 3.4.1

```
XML Parsing Error: error in processing external entity reference
Location: chrome://smarttemplate4/content/settings.xhtml
Line Number 4, Column 94: <!ENTITY % localeDTD SYSTEM "chrome://smarttemplate4/locale/smartTemplate-settings.dtd"> %localeDTD;
```

**Comment by RealRaven2000** [comment]
> Trying to open settings:
> 
> TB: 78.7.1 (tested on 32/64 bit) - Locale "it"
> ST: 3.4.1
> 
> ```
> XML Parsing Error: error in processing external entity reference
> Location: chrome://smarttemplate4/content/settings.xhtml
> Line Number 4, Column 94: <!ENTITY % localeDTD SYSTEM "chrome://smarttemplate4/locale/smartTemplate-settings.dtd"> %localeDTD;
> ```

It looks like the translation system of google inserted some double quotes, translating the original string:

`<!ENTITY header.set.from "sets 'from' address. This only accepts mail addresses from list of identities.">`

`<!ENTITY header.set.from "imposta l'indirizzo "da". Questo accetta solo indirizzi e-mail dall'elenco di identità.">`

which generates a parsing error in the Italian locale. Apologies, it's a lot of work with that many translations.

**Comment by RealRaven2000** [comment]
Quick fix versions:

Tb78: [smartTemplate-fx-3.4.2.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5937709/smartTemplate-fx-3.4.2.zip)
Tb68: [smartTemplate-fx-2.14.2.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5937711/smartTemplate-fx-2.14.2.zip)

As we cannot upload xpi files, you can use these zip files instead. download and drag the file into Thunderbird Add-ons Manager to install.

**Comment by matteotrubini** [comment]
LGTM 👏

**Comment by RealRaven2000** [comment]
I already have submitte 2.14.2 to atn so that it can be reviewed ASAP - once that's done I am going to upload 3.4.2 (I have to always upload the Tb68 version first because it "hides" the modern version, and I cannot submit 2 versions at the same time, unfortunately. Here is hoping there is a kind soul in the reviewers group that may give it a few minutes over the weekend. With some luck not too many users will be inconvenienced as many use Thunderbird only during office hours.

**Comment by RealRaven2000** [comment]
Had to bump 2.14.2 to 2.14.2.1 because I accidentally buymped the minver for Semonkey (which was also 2.14) instead of the actual Add-on version in install.rdf - which may have some weird consequences for users of Thunderbird 60 and older. According to statistics there are still over 1000...

**Comment by RealRaven2000** [comment]
Fixed and reviewed by atn, thanks for reporting!
