### ISSUE TITLE
Expand multiple recipients with %to(firstname)% in New Mail Template

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplate4#135]
When replying to an email we expect the variable `%from(firstname)%` to fill in all recipient names. This apparently doesn't happen when writing a new mail with multiple "To:" lines:

![image](https://user-images.githubusercontent.com/6314674/121180851-3ca4a600-c859-11eb-8d20-b1c6baea1d5d.png)

expected behavior - in this example the field should update to 
"Dear Raven, SeaMonkey"
listing all recipients.

The error was reported on SmartTemplates 2.15 (Thunderbird 68) but can also be reproduced on Thunderbird 78 with v3.5.4

**Comment by RealRaven2000** [comment]
I also did a test (Thunderbird 78) with "reply all" - the same issue applies - only the first recipient name is resolved:

![image](https://user-images.githubusercontent.com/6314674/121182102-a70a1600-c85a-11eb-8930-1b9d721ad0ba.png)

Expected behavior:

The answer (using "Dear `%from(firstname,lastname)%`,") should read as follows:

"Dear Axel Grude, yaël SeahMonkey,"

**Comment by RealRaven2000** [comment]
> Debugging this - I am using the function extractHeader("from") to get the original from header. It only returns a single address at the moment even if I "reply all":
> 

There is a actually a fallacy here - there is always only a singular "from" header (the other recipients would be listed in "to"). This case cannot be easily covered with the %from% variable. The original report (in a new email) is working from a new email and doesn't use mail headers anyway, so this needs to be tested separately.

But this opens a bigger question: I was thinking for a while that we should have a universal variable that covers the recipients of an email (the final To: when we send mail)  and works both  the same in reply and new mails - I think this cannot be easily covered with the existing keywords `%to%` and `%from%` without breaking compatibility. I think creating an entirely new variable for this case would be in order. Maybe something like `%recipient.to%` and `%recipient.cc%` - which I will deal with in a separate github issue.

**Comment by RealRaven2000** [comment]
Testing the %to(firstname)% case it actually does work as expected in Thunderbird 78, but not in Thunderbird 68, so I am going to fix it there first.

**Comment by RealRaven2000** [comment]
So here is a test version for Thunderbird 68. It generates an array of the "to" addresses (or any other address fields) in the "deferred variables" that you can use in "New Mail" templates. The character in between can be configures in the advanced tab:

![image](https://user-images.githubusercontent.com/6314674/121202142-f8bb9c00-c86c-11eb-982f-ad7151821bbb.png)

[smartTemplate-fx-2.16pre2.zip](https://github.com/RealRaven2000/SmartTemplate4/files/6617293/smartTemplate-fx-2.16pre2.zip)

To install, download the zip file and drag it into Thunderbird 68 Add-ons Manager. (Github doesn't support attaching xpi / add-on files in comments but zip works fine).

**Comment by stephankoenig** [comment]
Great! Works for me with Thunderbird 68!

Thank you!

**Comment by stephankoenig** [comment]
I started seeing double comas. 
Like 
Dear Pam, , 
I guess this is only on creating new emails with one recipient, but I have not done enough testing.

**Comment by RealRaven2000** [comment]
> I started seeing double comas.
> Like
> Dear Pam, ,
> I guess this is only on creating new emails with one recipient, but I have not done enough testing.

Are there special characters (especially commas) in the recipient's address book entry? I am splitting the recipient string using the "," delimiter and this problem could happen if a recipient's name contained a comma. If you can't see it in the address itself, try disabling the advanced feature "resolve names from Address Book" to see if it stops that.

**Comment by stephankoenig** [comment]
No special characters in the recipient's address book entries, tested on two. Turning off "resolve names from Address Book" does not stop it.

**Comment by RealRaven2000** [comment]
OK - here is a new vuild for Thunderbird 68 and earlier, which deals with the "unnecessary comma at the end" issue. Turns out  that it iterates through the empty lines on the address widget and adds these in Thunderbird 68. So I guarded against that, which should work better now:

[smartTemplate-fx-2.16pre4.zip](https://github.com/RealRaven2000/SmartTemplate4/files/6656985/smartTemplate-fx-2.16pre4.zip)

**Comment by RealRaven2000** [comment]
because it appears to add it's own objects to messenger.<namespace> and I can't really see how that works without interfering with the other Add-ons, should they use the same name...

**Comment by stephankoenig** [comment]
The first tests were okay. Thank you!

**Comment by RealRaven2000** [comment]
Working versions released today: 2.16 for Thunderbird 68, 3.6 for Thunderbird 78
