### ISSUE TITLE
TB 91 is not supported

### ISSUE THREAD

**Issue by smallersign** [RealRaven2000/SmartTemplate4#144]
SmartTemplate4 is not working TB91

**Comment by RealRaven2000** [comment]
I am just testing compatibility, can you please check 
https://github.com/RealRaven2000/SmartTemplate4/issues/127

there is a working prerelease there!

**Comment by smallersign** [comment]
Thank for your information.

**Comment by RealRaven2000** [comment]
Just reopening the issue for other people to see until SmartTemplates 3.7 is fully released.

Latest test version is at issue #127 (make SmartTempaltes compatible with Tb91)

**Comment by RealRaven2000** [comment]
All done. Implemented in 3.7 released on 20/08/2021
