### ISSUE TITLE
Using TB 91 and SmartTemplate is not working after restart

### ISSUE THREAD

**Issue by risfamu** [RealRaven2000/SmartTemplate4#146]
I have Thunderbird 91 on Macbook Air M1 and install smart template smoothly. It can run perfectly until i need to close my TB and open the app again. When i open TB again, i found that smart template is not working. It's still "enabled" in my "Managed your extension" page, but not working. And configuration button is missing. 

The workaround --> uninstall / remove; restart TB; and download + install add-ons again. 

Hopefully there is more permanent solution for this.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/89885794/131597651-a8807db8-7a00-46e1-815e-1e3ecfdcfa20.png">

**Comment by RealRaven2000** [comment]
what version of SmartTemplates is running? is it possible that something installs an older version  over the one you downloaded? 
pleasecreate an error console log with JavaScript error console.  instructions with details can be found here:

https://smarttemplates.quickfolders.org/support.html

**Comment by RealRaven2000** [comment]
we can get even more useful info if you enable debug mode on the advanced settings tab. there are some added lines logged by the Background script when SmartTempkates shuts down/ starts up.

**Comment by risfamu** [comment]
honestly, i'm not sure where can find error console on TB 91. but here it is some screenshot :

Can't find config menu here :
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/89885794/131641901-67002e75-808f-4cdc-9bad-464927705d85.png">

Smarttemplate version 3.7. Downloaded today :
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/89885794/131641809-7284cbcd-6b73-4ef9-886a-b6a53ac88501.png">

From the menu "debug add ons" :
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/89885794/131641628-6527415d-0a21-4f67-a523-0954fcc7d508.png">

"Console" tab view :
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/89885794/131641506-8dc869ed-be4d-4ddf-a7b8-c79565d08285.png">

**Comment by RealRaven2000** [comment]
we can get even more useful info if you enable debug mode on the advanced settings tab. there are some added lines logged by the Background script when SmartTempkates shuts down/ starts up.

> honestly, i'm not sure where can find error console on TB 91. 

I linked you an article
https://smarttemplates.quickfolders.org/support.html

ctrlshift j or tools /web dev tools/ error console.

**Comment by RealRaven2000** [comment]
if you get the real error console working please try its right click menu:.  export visible messages to clipboard.  text logs are 100 times easier to process than screenshot logs

**Comment by risfamu** [comment]
ctrl+shift+j

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89885794/131645326-51a31c02-c1e1-479d-8d25-fe946f91aa3d.png">

**Comment by jobisoft** [comment]
What other add-ons do you have installed. Any change if you disable all of them, except SmartTemplate?

**Comment by RealRaven2000** [comment]
I wonder what's up with "can't find profile directory" did you recently make changes to your profile?

**Comment by risfamu** [comment]
> What other add-ons do you have installed. Any change if you disable all of them, except SmartTemplate?

As long as I aware, I only install 1 addon : smartemplate. But it seems I have 2 extension : device theme (TB default? Don't know when it is installed) and smart template

**Comment by RealRaven2000** [comment]
could you try and find your profiles.ini file and post it here?
see https://support.mozilla.org/en-US/kb/profiles-where-thunderbird-stores-user-data on where to find on mac

**Comment by RealRaven2000** [comment]
also do you run any resident antivirus checkers? might make sense to read their logs.

**Comment by risfamu** [comment]
> I wonder what's up with "can't find profile directory" did you recently make changes to your profile?

Before installing any add-ons, I migrate mail file from my TB from my previous laptop to my new laptop using "copy" file directly to profile folder in order to restore my local copy of email. And TB worked ever since.

**Comment by risfamu** [comment]
> also do you run any resident antivirus checkers? might make sense to read their logs.

Trend micro. I already checked its logs, can't find anything.

**Comment by RealRaven2000** [comment]
Can you provide your profile.ini and also the path and name of your profile please? should be something like `auiohw2o4.default` (the first part of the profile name is random)

**Comment by risfamu** [comment]
> Can you provide your profile.ini and also the path and name of your profile please? should be something like `auiohw2o4.default` (the first part of the profile name is random)

This is my profile.ini :
<img width="708" alt="image" src="https://user-images.githubusercontent.com/89885794/131695599-89ae0041-687d-4f85-89f3-8170227435c0.png">

This is the content of my default profile :
<img width="627" alt="image" src="https://user-images.githubusercontent.com/89885794/131695817-0c5e7f38-874a-4217-9981-7ba12de8f347.png">

**Comment by risfamu** [comment]
Just adding some more information. 

When TB crashed, the log looks like this : 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/89885794/131700969-2c364834-58da-457b-8535-28befef28020.png">
 

> AbortMessage: ###!!! ABORT: file resource://gre/modules/addons/XPIProvider.jsm:2602
AdapterVendorID: 0x106b
Add-ons: smarttemplate4%40thunderbird.extension:3.7,default-theme%40mozilla.org:1.2,google%40search.mozilla.org:1.0,ddg%40search.mozilla.org:1.0,amazondotcom%40search.mozilla.org:1.1,wikipedia%40search.mozilla.org:1.0,bing%40search.mozilla.org:1.0
AsyncShutdownTimeout: {"phase":"profile-change-teardown","conditions":[{"name":"Extension shutdown: smarttemplate4@thunderbird.extension","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2602,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2602","resource://gre/modules/AsyncShutdown.jsm:observe:575","resource:///modules/MailUtils.jsm:restartApplication:47","chrome://messenger/content/mailCore.js:safeModeRestart:780","chrome://messenger/content/messenger.xhtml:oncommand:1"]}]}
AvailablePhysicalMemory: 85573632
AvailableSwapMemory: 979107840
BuildID: 20210824180134
ContentSandboxCapable: 1
ContentSandboxLevel: 1
CrashTime: 1630510512
DOMIPCEnabled: 1
FramePoisonBase: 9223372036600922112
FramePoisonSize: 16384
InstallTime: 1630030142
MozCrashReason: MOZ_CRASH()
Notes: FP(D00-L1000-W00000000-T000) WR? WR+ OMTP? OMTP- GL Context? GL Context+ xpcom_runtime_abort(###!!! ABORT: file resource://gre/modules/addons/XPIProvider.jsm:2602)
ProductID: {3550f703-e582-4d05-9a08-453d09bdfdc6}
ProductName: Thunderbird
PurgeablePhysicalMemory: 0
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 618
ShutdownProgress: profile-change-teardown
StartupCrash: 0
StartupTime: 1630509917
TelemetryEnvironment: {"build":{"applicationId":"{3550f703-e582-4d05-9a08-453d09bdfdc6}","applicationName":"Thunderbird","architecture":"aarch64","buildId":"20210824180134","version":"91.0.3","vendor":null,"displayVersion":"91.0.3","platformVersion":"91.0.1","xpcomAbi":"aarch64-gcc3","updaterAvailable":true},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":8192,"virtualMaxMB":null,"cpu":{"extensions":["hasNEON"]},"os":{"name":"Darwin","version":"20.6.0","locale":"en-ID"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"adapters":[{"description":null,"vendorID":"0x106b","deviceID":null,"subsysID":null,"RAM":0,"driver":null,"driverVendor":null,"driverVersion":null,"driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1440,"screenHeight":900,"scale":2}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"wrQualified":{"status":"available"},"webrender":{"status":"available"},"wrCompositor":{"status":"available"},"wrSoftware":{"status":"available"},"openglCompositing":{"status":"available"},"omtp":{"status":"disabled:FEATURE_FAILURE_DISABLED"}}},"appleModelId":"MacBookAir10,1"},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":false,"telemetryEnabled":false,"locale":"en-US","intl":{},"update":{"channel":"release","enabled":true},"userPrefs":{"browser.search.region":"ID","privacy.donottrackheader.enabled":true,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":1,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":null},"profile":{}}
ThreadIdNameMapping: 6:"IPC I/O Parent",10:"Permission",11:"JS Watchdog",13:"TaskController Thread #0",17:"TaskController Thread #4",14:"TaskController Thread #1",15:"TaskController Thread #2",16:"TaskController Thread #3",18:"TaskController Thread #5",19:"TaskController Thread #6",20:"TaskController Thread #7",22:"Timer",23:"Cache2 I/O",24:"Cookie",27:"Worker Launcher",28:"IPDL Background",29:"Renderer",30:"WRWorker#0",31:"WRWorker#1",33:"WRWorker#3",35:"WRWorker#5",40:"WRWorkerLP#2",37:"WRWorker#7",38:"WRWorkerLP#0",41:"WRWorkerLP#3",44:"WRWorkerLP#6",32:"WRWorker#2",39:"WRWorkerLP#1",42:"WRWorkerLP#4",34:"WRWorker#4",45:"WRWorkerLP#7",36:"WRWorker#6",43:"WRWorkerLP#5",46:"Compositor",48:"ImageIO",51:"StyleThread#0",52:"StyleThread#1",53:"StyleThread#2",54:"StyleThread#3",55:"StyleThread#4",56:"StyleThread#5",57:"ImageBridgeChld",64:"ProcessHangMon",65:"GMPThread",65:"TRR Background",68:"QuotaManager IO",92:"WRSceneBuilder#3",93:"WRSceneBuilderLP#3",94:"WRRenderBackend#3",76:"mozStorage #2",79:"WRSceneBuilder#4",81:"WRRenderBackend#4",80:"WRSceneBuilderLP#4",80:"mozStorage #5",82:"HTML5 Parser",87:"mozStorage #6",88:"localStorage DB",98:"mozStorage #8",99:"DOM Worker",92:"URL Classifier",88:"BackgroundThreadPool #3",84:"Shutdown Hang Terminator",76:"mozStorage #9",
Throttleable: 1
TotalPhysicalMemory: 8589934592
URL: about:blank
UptimeTS: 595.25
Version: 91.0.3
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by jobisoft** [comment]
Is any of this happening in a fresh profile?

**Comment by risfamu** [comment]
> > Is any of this happening in a fresh profile?
> 
> A fresh profile might indeed be the safest (and most performant) way, once you set up your server settings / email address you can go offline (shut down thunderbird) and copy over your Mail and ImapMail subfolders into the new profile. Once you are sure that it works, I can help you migrate the SmartTemplates settings from prefs.js too.

So, creating new fresh profile seem to be solution? i'll try creating new one. will update you once it's ready.

**Comment by RealRaven2000** [comment]
> > A fresh profile might indeed be the safest (and most performant) way, once you set up your server settings / email address you can go offline (shut down thunderbird) and copy over your Mail and ImapMail subfolders into the new profile. Once you are sure that it works, I can help you migrate the SmartTemplates settings from prefs.js too.
> 
> So, creating new fresh profile seem to be solution? i'll try creating new one. will update you once it's ready.

Any update on this. I see this issue is still closed.

**Comment by risfamu** [comment]
> > > A fresh profile might indeed be the safest (and most performant) way, once you set up your server settings / email address you can go offline (shut down thunderbird) and copy over your Mail and ImapMail subfolders into the new profile. Once you are sure that it works, I can help you migrate the SmartTemplates settings from prefs.js too.
> > 
> > 
> > So, creating new fresh profile seem to be solution? i'll try creating new one. will update you once it's ready.
> 
> Any update on this. I see this issue is still closed.

Hi, 

Sorry for late update. I've created new fresh profile, re-setup everything, and now everything run smoothly. 

Thanks for your support.
