### ISSUE TITLE
reply template applied twice in thunderbird 91.2.0

### ISSUE THREAD

**Issue by jtomfarrar** [RealRaven2000/SmartTemplate4#155]
I updated to thunderbird 91.2.0 yesterday, and the automatically generated greeting and signature appears twice when replying to a message.  This is SmartTemplates version 3.7 (which I really love!).

For example:
'''
Hi Emerson,

Thank you,
Tom

Hi Emerson,

Thank you,
Tom
'''

**Comment by RealRaven2000** [comment]
Can you test the version here please?

https://github.com/RealRaven2000/SmartTemplates/issues/139#issuecomment-971998632

You can find there 2 prereleases:

smartTemplate-fx-3.8.1pre10.zip for Tb 78 and later
smartTemplate-fx-2.17pre102.zip for Tb68

This specifically addresses the Tb Conversations plugins and the way it handles it's own proprietary Reply button. If it's resolved by that I would like to close this issue and mark as duplicate of #139

**Comment by jtomfarrar** [comment]
The new version seems to work perfectly!  Thank you very much.
