### ISSUE TITLE
(Tb91) Cannot switch spell checker language.

### ISSUE THREAD

**Issue by goozak** [RealRaven2000/SmartTemplate4#158]
Started receiving this error since latest update (3.7 on TB 91.2.0):

> Cannot switch spell checker language. Have you installed the correct dictionary?
> gSpellChecker.mInlineSpellChecker is null

No changes have been made to my templates, have been using `%spellcheck(fr)%` without issue for a while.

**Comment by RealRaven2000** [comment]
> Started receiving this error since latest update (3.7 on TB 91.2.0):
> 
> > Cannot switch spell checker language. Have you installed the correct dictionary?
> > gSpellChecker.mInlineSpellChecker is null
> 
> No changes have been made to my templates, have been using `%spellcheck(fr)%` without issue for a while.

Could be yet another change in the internal structure of Thunderbird 92, let me check...

**Comment by RealRaven2000** [comment]
Can you try this quick fix version:

[smartTemplate-fx-3.8pre211.zip](https://github.com/RealRaven2000/SmartTemplates/files/7392794/smartTemplate-fx-3.8pre211.zip)

This is still using legacy methods for accessing the spell checked a more permanent solution will be  to use a [Web API](https://webextension-api.thunderbird.net/en/latest/index.html) and calling the spellcheck via a background script - but there I have not found access to the spellcheck settings in any of the official APIs compose, composeAction and composeScripts. So I am just doing it the "hacky" way, following what Thunderbird itself does.

To install, download the zip file, and then drag it into Thunderbird Add-ons Manager.
