### ISSUE TITLE
"expand all" inside new settings variables page doesn't work

### ISSUE THREAD

**Issue by MarkyMarkDE** [RealRaven2000/SmartTemplate4#312]
In the Variables Window the Link on Top left "Expand all" do not work.
Console do not write any error after click.

SmartTemplates-4.7.1pre24
Linux Ubuntu 22.04.4 LTS
Thunderbird 128.0ESR

**Comment by RealRaven2000** [comment]
Good find! Should be easy to fix. I also had some extra script functionality that used to copy the clicked variable over into Account templates - but that's not visible at the same time anymore. should it copy it to clipboard instead?

**Comment by RealRaven2000** [comment]
Fixed:

[smartTemplate-fx-4.7.1pre32.zip](https://github.com/user-attachments/files/16599433/smartTemplate-fx-4.7.1pre32.zip)

---

To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents).

**Comment by MarkyMarkDE** [comment]
> Fixed:
> 
> [smartTemplate-fx-4.7.1pre32.zip](https://github.com/user-attachments/files/16599433/smartTemplate-fx-4.7.1pre32.zip)
> 
> To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents).

fix work in one direction only, you can expand but not close all again - toggle

> should it copy it to clipboard instead?

This would be an option, but simple copy to clipboard isn't really user-friendly, maybe we need localized alert or something that makes sure, that the variable is copied to clipboard and the user now should select his template/case to paste it in or something.

**Comment by RealRaven2000** [comment]
> > [smartTemplate-fx-4.7.1pre32.zip](https://github.com/user-attachments/files/16599433/smartTemplate-fx-4.7.1pre32.zip)
> > To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents).
> 
> fix work in one direction only, you can expand but not close all again - toggle

that didn't work like that ever (it would have to keep track and also change the text), that would be a new feature request. please raise hits one as separate issue.

**Comment by MarkyMarkDE** [comment]
> > > [smartTemplate-fx-4.7.1pre32.zip](https://github.com/user-attachments/files/16599433/smartTemplate-fx-4.7.1pre32.zip)
> > > To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents).
> > 
> > 
> > fix work in one direction only, you can expand but not close all again - toggle
> 
> that didn't work like that ever (it would have to keep track and also change the text), that would be a new feature request. please raise hits one as separate issue.

done

**Comment by RealRaven2000** [comment]
Fixed in 4.8 - published 03/09/2024
