### ISSUE TITLE
Global settings for statusbar icon do not work

### ISSUE THREAD

**Issue by MarkyMarkDE** [RealRaven2000/SmartTemplate4#313]
In Global settings we have the option for the statusbar icon (bottom right), but nothing worked here.

SmartTemplates-4.7.1pre32
Linux Ubuntu 22.04.4 LTS
Thunderbird 128.0ESR

![Bildschirmfoto vom 2024-08-13 14-28-29](https://github.com/user-attachments/assets/e9e4b8c6-5135-44e2-9426-c53f6758d30c)

**Comment by RealRaven2000** [comment]
yeah - missing the notification to the background page. I believe it should change the setting but it's not telling Thunderbird to reflect the change directly.

**Comment by MarkyMarkDE** [comment]
> yeah - missing the notification to the background page. I believe it should change the setting but it's not telling Thunderbird to reflect the change directly.

If possible, please try to fix, or we have to remove all from our scripts etc., we have other access ways for the addon, we can miss this if it is not possible to make it functionaly again.

**Comment by MarkyMarkDE** [comment]
This means, if the user will open the settings, we have the only way from the Addons page click on the wrench icon

**Comment by RealRaven2000** [comment]
By the way, it is always good to look at error console:

![image](https://github.com/user-attachments/assets/dd43e885-2b1e-4fa0-8b24-c97788d5c086)

it often saves time to jump to the correct place in the code faster.

**Comment by MarkyMarkDE** [comment]
> By the way, it is always good to look at error console:
> 
> ![image](https://private-user-images.githubusercontent.com/6314674/357413230-dd43e885-2b1e-4fa0-8b24-c97788d5c086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjgwMjcsIm5iZiI6MTcyMzU2NzcyNywicGF0aCI6Ii82MzE0Njc0LzM1NzQxMzIzMC1kZDQzZTg4NS0yYjFlLTRmYTAtOGIyNC1jOTc3ODhkNWMwODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTY0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAyOTg1NzMzZjQxZmI2NTQ4Zjg5ZjFiOTc1YjMyMzVkYTYwN2U0Y2UwMzk2ZWU0ZTBlMmQ0MTJhZDczOTNlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dB3x1K7tbEsvVPJd_oFxlMDHpjwpUpd6FOpNHgiMaUQ)
> 
> it often saves time to jump to the correct place in the code faster.

yes, you are right. Mostly i do this but in this case not ...

**Comment by RealRaven2000** [comment]
> > By the way, it is always good to look at error console:
> > ![image](https://private-user-images.githubusercontent.com/6314674/357413230-dd43e885-2b1e-4fa0-8b24-c97788d5c086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjgwMjcsIm5iZiI6MTcyMzU2NzcyNywicGF0aCI6Ii82MzE0Njc0LzM1NzQxMzIzMC1kZDQzZTg4NS0yYjFlLTRmYTAtOGIyNC1jOTc3ODhkNWMwODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTY0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAyOTg1NzMzZjQxZmI2NTQ4Zjg5ZjFiOTc1YjMyMzVkYTYwN2U0Y2UwMzk2ZWU0ZTBlMmQ0MTJhZDczOTNlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dB3x1K7tbEsvVPJd_oFxlMDHpjwpUpd6FOpNHgiMaUQ)
> > it often saves time to jump to the correct place in the code faster.
> 
> yes, you are right. Mostly i do this but in this case not ...

no worries, working on this now, will post a fix shortly...

**Comment by RealRaven2000** [comment]
Implemented the functions:

[smartTemplate-fx-4.7.1pre41.zip](https://github.com/user-attachments/files/16603438/smartTemplate-fx-4.7.1pre41.zip)

---

To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents).

**Comment by MarkyMarkDE** [comment]
> Implemented the functions:
> 
> [smartTemplate-fx-4.7.1pre41.zip](https://github.com/user-attachments/files/16603438/smartTemplate-fx-4.7.1pre41.zip)
> 
> To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents).

confirmed, it's fully working again, thank you.

**Comment by RealRaven2000** [comment]
please leave issues open until the final version is released to the public

**Comment by RealRaven2000** [comment]
4.8 - published 03/09/2024
