### ISSUE TITLE
Feature Request: convert "expand all" in variables page into toggle

### ISSUE THREAD

**Issue by MarkyMarkDE** [RealRaven2000/SmartTemplate4#314]
Please make the "expand all" on top left of the variables window as toggle again, like in legacy addon.
See additional #312

**Comment by RealRaven2000** [comment]
Here is a test version:

[smartTemplate-fx-4.7.1pre46.zip](https://github.com/user-attachments/files/16604099/smartTemplate-fx-4.7.1pre46.zip)

to do: add localization to the "Collapse All" function. Maybe I will rename it to "collapse all chapters" which should also generate better translations in chatGPT.

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
4.8 - published 03/09/2024
