### ISSUE TITLE
Configure Menu item... not working as expected.

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplate4#318]
The menu command  "Answer >> configure menu item" is not working as expected:

![image](https://github.com/user-attachments/assets/dbafef74-fb2d-492c-bc1a-1fc0e3ae4685)

it should open settings and then select the "template files" menu and pre-select the "reply" tab.

**Comment by RealRaven2000** [comment]
Here is a test version:

[smartTemplate-fx-4.8pre86.zip](https://github.com/user-attachments/files/16736814/smartTemplate-fx-4.8pre86.zip)

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by MarkyMarkDE** [comment]
now fix #313 didn't work again

**Comment by RealRaven2000** [comment]
4.8 - published 03/09/2024
