### ISSUE TITLE
SmartTemplates ignored when creating an email from the Thunderbird taskbar context menu #272

### ISSUE THREAD

**Issue by goozak** [RealRaven2000/SmartTemplate4#322]
This is the same as #272, which was previously fixed.

When right-clicking the Thunderbird icon on the **Windows taskbar** and selecting "Write new message", the message created doesn't contain the template usually applied to a new message (like when I use the "+ New Message" button above the Folder Pane).

Windows 10 / Thunderbird 128.2.0esr (64-bit) / SmartTemplates 4.8.1

**Comment by RealRaven2000** [comment]
In that case, I saw an exception (parameter is null). here is a fix that works for me:

[smartTemplate-fx-4.8.2pre29.zip](https://github.com/user-attachments/files/17017284/smartTemplate-fx-4.8.2pre29.zip)

-----

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by goozak** [comment]
That fix works for me too!  Thanks  👍

**Comment by RealRaven2000** [comment]
Fixed in in 4.9 - published 11/11/2024
