### ISSUE TITLE
Replying to a replied-to email removes previously replied text

### ISSUE THREAD

**Issue by ckeydel** [RealRaven2000/SmartTemplate4#39]
Often, I follow-up on emails that I have previously answered and if there hasn't been another reply from the contact in the meantime I use my own reply for the follow-up so that my previous answer is kept. For that, I use "Reply" or "Reply-all" on my last sent email.

With ST4 enabled, in most cases this will completely remove the text I added to my previous reply, so in the email I see the original email from the contact, my added header from my previous response but not the previous signature and also not the previous text. I can understand that the signature is removed (even that should be an option, though), but my previous text is essential and must not be silently removed (well, the removal is silent, my reaction is not! ;-)). In this example, the highlighted space marks where the previous text and signature was removed:

![image](https://user-images.githubusercontent.com/52654513/73063421-069e9600-3e9f-11ea-9585-90027459f06a.png)

This happens often, but not always and I haven't figured out the mechanics behind it. Nothing terribly complicated or advanced in my settings for the affected accounts either, e.g.:

![image](https://user-images.githubusercontent.com/52654513/73063090-3ef1a480-3e9e-11ea-8f99-9e6f13792dc5.png)

It doesn't happen if I keep the shift key pressed to generate a plain-text reply email, but this is usually not an option.

**Comment by ckeydel** [comment]
Follow-up: Curiously, the location where the text is removed is where TB puts the file link if I use the FileLink feature:

![image](https://user-images.githubusercontent.com/52654513/73065502-fa690780-3ea3-11ea-9e94-74b99f527ddf.png)

I would expect this to happen above the new signature where I added my new text. Which is what TB does when I disable ST4 (just checked). So, there appears to be several issues with such emails when ST4 is used.

**Comment by RealRaven2000** [comment]
> Follow-up: Curiously, the location where the text is removed is where TB puts the file link if I use the FileLink feature:
> 
> I would expect this to happen above the new signature where I added my new text. Which is what TB does when I disable ST4 (just checked). So, there appears to be several issues with such emails when ST4 is used.

Can you open a separate issue for the fileline stuff?

**Comment by RealRaven2000** [comment]
> With ST4 enabled, in most cases this will completely remove the text I added to my previous reply, so in the email I see the original email from the contact, my added header from my previous response but not the previous signature and also not the previous text. I can understand that the signature is removed (even that should be an option, though), but my previous text is essential and must not be silently removed (well, the removal is silent, my reaction is not! ;-)). In this example, the highlighted space marks where the previous text and signature was removed:

this is very strange and unexpected. can you post your template text? SmartTemplate is not supposed to touch anything within the `<blockquote>` element.

I suspect it's a side effect of the "toxic" setting "Replace line breaks with `<br>`". 

![image](https://user-images.githubusercontent.com/6314674/73066734-b32c4800-3e9e-11ea-9717-b7ccadfcfc5c.png)

I wish I had removed that setting 7 years ago when I took over development. Can you please disable this and insert `<br>` like in a proper HTML code?

In any case, please export your settings with the "_Save Template..._" button and attach to the comment:

![image](https://user-images.githubusercontent.com/6314674/73066807-f090d580-3e9e-11ea-810a-3b0044800918.png)

**Comment by ckeydel** [comment]
Just unchecked that option and no change, it still happens. Attached the exported template.
[myemail@mydomain - My Name.zip](https://github.com/RealRaven2000/SmartTemplate4/files/4108274/myemail%40mydomain.-.My.Name.zip)

**Comment by ckeydel** [comment]
It seems that "simple" emails and emails between TB users are not affected. For example, I replied to the GitHub notification email and put your email address in, sent that. I can reply to that sent email no problem, all the text is there. But most other email originally from god-knows-what email client, the problem happens. So my assumption is that it is "something" in the original emails that is carried over to the replies and makes this fail.

**Comment by RealRaven2000** [comment]
> 
> 
> Just unchecked that option and no change, it still happens. Attached the exported template.
> [myemail@mydomain - My Name.zip](https://github.com/RealRaven2000/SmartTemplate4/files/4108274/myemail%40mydomain.-.My.Name.zip)
> 
> BTW my TB version is 60.9.1 (64-bit). Perhaps it is some unusual HTML in my signature that's tripping it? The default signature (HTML) is
> 
> ```
> <div class="moz-signature">
> <font face="Helvetica, Arial, sans-serif">
> <p style="color:black">
> <br>
> <small>Chris
> </small></font>
> </div>
> ```

I can see your problem right there. You are missing the closing `</p>` tag. I think that causes major confusion to Thunderbird.
Also, _please_ get rid of `<font>` ! it's deprecated. instead put the font properties in a separate style tag or as part of the `<div>`.

try this instead:

```
<div class="moz-signature" style="font-family:Helvetica, Arial, sans-serif; color:black">
  <p>
    %cursor%
    <br>
  </p>
  <p>  
    <small>Chris
    </small>
  </p>
</div>
```

**Comment by RealRaven2000** [comment]
Pretty sure I can flag this one as `invalid`. The behaivor is actually by design, and it's Thundebird's behavior.

**Comment by ckeydel** [comment]
Agreed, the moz-signature was tripping it. Removing it made it work as intended. Thanks!
