### ISSUE TITLE
Using FileLink puts the link in wrong location in replied-to reply emails

### ISSUE THREAD

**Issue by ckeydel** [RealRaven2000/SmartTemplate4#40]
Linked to this issue:
https://github.com/RealRaven2000/SmartTemplate4/issues/39#issue-554664370

The location where the text is removed is where TB puts the file link if I use the FileLink feature:

![image](https://user-images.githubusercontent.com/52654513/73068338-42d7f380-3eab-11ea-8b89-722738c18332.png)

I would expect this to happen above the new signature where I added my new text. Which is what TB does when I disable ST4 (just checked). So, there appears to be several issues with such emails when ST4 is used.

**Comment by ckeydel** [comment]
The linked issue is now closed, and the links are now placed after the signature, which is by design I guess. Or do you see a way to place it before the signature?

**Comment by RealRaven2000** [comment]
> The linked issue is now closed, and the links are now placed after the signature, which is by design I guess. Or do you see a way to place it before the signature?

I need to look into it, can you do a description of how to get there? With filelinks, Thunderbird currently does all the work, so I am not aware of them to a deep level of detail
