### ISSUE TITLE
Incorrect information (license, payment?) on addons.thunderbird.net

### ISSUE THREAD

**Issue by jefferyto** [RealRaven2000/SmartTemplate4#6]
According to [commit history](https://github.com/RealRaven2000/SmartTemplate4/commit/33870a01e2e8f9f4d24fc02ca5792ae73937e7db#diff-98cd14c95bb22f9d397da0603a77d950), the addon license was changed from GPL3 to CC BY-ND 4.0 in version 1.5.

Currently (with version 2.2.2), the addon is still listed as licensed under GPL3. (I do not mean in the addon / version description, I mean in the addon metadata that causes the description page to include "Released under GNU General Public License, version 3.0" in the right-side column.) Please correct this.

In fact, except for [2.0](https://addons.thunderbird.net/en-US/thunderbird/addon/smarttemplate4/versions/2.0), [every version](https://addons.thunderbird.net/en-US/thunderbird/addon/smarttemplate4/versions/) since (and including) 1.5 has been listed as GPL3 (again, in the addon metadata). It would be good if these past versions can be corrected as well (if possible).

**Comment by RealRaven2000** [comment]
ok, how do I do this? I changed it when I released 2.0 I thought this would carry forward.

**Comment by jefferyto** [comment]
Wish I could help, but I'm not an addon developer (only have a few search addons) so I don't know how to change it.

Also, I believe there is a flag to indicate if an addon has [features that require payment](https://discourse.mozilla.org/t/is-it-possible-to-develop-a-paid-extension/30757/2). From the [addons policies page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews#Content):

> Add-ons must disclose when payment is required to enable any functionality.

Not sure if you prefer I open another issue for this or if mentioning it here is enough.

**Comment by RealRaven2000** [comment]
I fixed it with some help from the guys at #tb-addon-reviewers. From what I can see, the required payment flag is actually set in the latest version, not sure where you saw it differently?

**Comment by jefferyto** [comment]
I guess I was expecting to see something like [this screenshot](https://discourse.mozilla.org/t/is-it-possible-to-develop-a-paid-extension/30757/5), but looking at some other paid addons ([ExQuilla for Exchange](https://addons.thunderbird.net/en-US/thunderbird/addon/exquilla-exchange-web-services/), [Owl for Exchange](https://addons.thunderbird.net/en-US/thunderbird/addon/owl-for-exchange/)) it doesn't appear it is displayed on the description page (assuming they also set the required payment flag).

I think both points have been addressed so I'll close this issue - thanks for your help :slightly_smiling_face:
