### ISSUE TITLE
Add a variable for quoted text

### ISSUE THREAD

**Issue by GreyShirt** [RealRaven2000/SmartTemplate4#61]
This variable would make it possible to insert the original text inside our custom template for Reply or Forward. 
Currently, replying looks like this (notice the quoted message is outside the blue template)
![current](https://user-images.githubusercontent.com/64785114/81000364-2e918400-8e14-11ea-8397-7bb459e6e2be.png)
With this feature, we could include the text in the template and style it.
![feature](https://user-images.githubusercontent.com/64785114/81000582-7d3f1e00-8e14-11ea-9c3e-64471c2cf6b6.png)

**Comment by RealRaven2000** [comment]
Very good idea. As I said in the email to the OP, we already had a variable that was a placeholder for the quoted text which worked with Stationery. 

When we had stationery, you were able to achieve this by using the `%quotePlaceholder%` variable. But it was a bit of a hack and based on functionality that Stationery itself brought to the table. I think it would be an awesome feature though.

![image](https://user-images.githubusercontent.com/6314674/81009059-d5454700-8e4b-11ea-9602-af795769bd5c.png)

As you can see, it just inserted a specially formatted<span>tag and Stationery would pick it up and do all the heavy lifting.  I need to inject the code that cuts out the complete `<blockquote>` part and reinserts it into the template.

**Comment by RealRaven2000** [comment]
This is super important and I pinned it for one of the next new features in Thunderbird 78

**Comment by RealRaven2000** [comment]
I have a test version for Thunderbird 78. Once the variable is encountered, the quote is removed from the bottom (top) of the email and moved to the place where the variable is in the template.
The variable is `%quotePlaceholder%` or `%quotePlaceholder(level)%`.
I added an optional parameter for the level of the quote - e.g.
`%quotePlaceholder(2)%` - this will preserve direct quotes (level 1) and requoted quotes (level 2) but remove any quotes on a lower level (older quotes). I reckon that the usual case would be a direct reply to a request maybe cleaning out unnecessary past items, or alternatively keeping a few more levels of or the complete conversation.

[smartTemplate-fx-3.3pre12.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5717949/smartTemplate-fx-3.3pre12.zip)

To install - drag zip file into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
... however, what's still missing is the removal of the quote header and moving it above the quote. It actually stays behind at the bottom as it is already generated at that time and it is not part of the quote content. The question is whether it should do that automatically or whether this should be triggered by a second variable %quoteHeader% (which is how Stationery might have done this)?

**Comment by RealRaven2000** [comment]
Another version, this one tries to "hoist up" the last generated quote header in front of the quoted material. This will also work if you used a single `<blockquote>` element to wrap the quote header in order to bring it to the same level (blue line on left) as the quote:

![image](https://user-images.githubusercontent.com/6314674/102662064-fa39c080-4175-11eb-8e22-fde7c2e5d58c.png)

[smartTemplate-fx-3.3pre14.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5718082/smartTemplate-fx-3.3pre14.zip)

To install - drag zip file into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
@GreyShirt were you able to test the new version posted above?

**Comment by RealRaven2000** [comment]
Here is a new prerelease version with fully localized documentation added in the  "Quote Manipulation" section:

![image](https://user-images.githubusercontent.com/6314674/103291307-55c04580-49e3-11eb-945d-621bb0f8ed89.png)

[smartTemplate-fx-3.3pre22.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5751056/smartTemplate-fx-3.3pre22.zip)
To install, drop zip file into Thunderbird Add-ons Manager

**Comment by RealRaven2000** [comment]
released for Thunderbird 68 in maintenance version 2,13 today. The Tb78 version will follow as soon as this one is reviewed on ATN.

**Comment by RealRaven2000** [comment]
Implemented in 3.3 released for Thunderbird 78 on 03/01/2021
