### ISSUE TITLE
%from% when replying to an already sent email

### ISSUE THREAD

**Issue by hauber** [RealRaven2000/SmartTemplate4#64]
When I reply to an already sent email (which is stored in the sent email folder), Thunderbird is clever enough not to change the sender and recipient. In the SmartTemplate4 template, however, I would need to change %from% to %to% to get the greeting right. It would save me some editing (or additional templates) if SmartTemplate4 adapted to this particular case automatically.

**Comment by RealRaven2000** [comment]
Definitely a problem. I am classifying this one as a bug.

SmartTemplate4 does all processing on startup of composer and extracts emails from the contextually last selected email  (so if you reply to or forward your own mails in a thread the "from" address is still yourself), 

I would need to look into the internal state of Thunderbird to see whether there is another flag in the message object that will tell me that Tb swapped out the "to" address. I think maybe in this case I would to have to use the same logic as if you were writing a new email... no won't work either we still need to determine the original sender.

I will have to think about that one. the main condition may be to check for whether the %to% address resolves to one of your own addresses, and then attempt finding correct counter measures.

**Comment by hauber** [comment]
TB's logic doesn't work in all cases. Recently I've sent an email from a tablet. If I reply to this one in TB, both the sender and receiver are my address.

I'd say if the from-address in the original mail is myself, then all the addresses should be copied as-is and not swapped. SmartTemplates4 then needs to compensate for this.

**Comment by RealRaven2000** [comment]
Fixed in 2.11.1 - released June 21st
