### ISSUE TITLE
Make SmartTemplate⁴ compatible with Thunderbird 78 ESR

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplate4#69]
Thunderbird 78 will not be able to install legacy Add-ons. As an interim step, all Add-ons need to be rewritten as "mail  extension experiments". This bug tracks all changes necessary and breaking bugs that may occur due to the transformation.

3rd party developers are invited to help with this task - I can pay you to an extent. Please contact me off list directly if you want to help.

**Comment by RealRaven2000** [comment]
Timeline: we intend to be ready by end of September, when 78.2 is auto-rolled out to the Tb68 users base. Please do not upgrade until then.

What happened - @TbSync helped me and @Opto with the first hard conversion step to a mail experiment with QuickFolders. We will finish that one first so that it runs completely with only minor functionality loss. Then we will apply the same changes to quickFilters (similar codebase) and last SmartTemplate⁴.

**Comment by PhilippSPOTTERON** [comment]
+1 (very important)

**Comment by RealRaven2000** [comment]
Still working on the QuickFolders conversion, which is going to my the first fully Tb78 compatible Add-on, I have just created a new code branch to do preparation work for converting SmartTemplate⁴:

https://github.com/RealRaven2000/SmartTemplate4/tree/ESR78

If you are a developer please leave a comment here for a collaboration request.

We will be following the new upgrade guide here:
https://github.com/thundernest/addon-developer-support/wiki/Using-the-WindowListener-API-to-convert-a-Legacy-Overlay-WebExtension-into-a-MailExtension-for-Thunderbird-78

Since we will still be using the old XPCOM functions from within the confines of the "Mail extension experiment" framework, we hope to not lose any functionality in this step. The next 12 months can then be used to replace these functions with APIs (some of which still have to be designed and implemented by the Thunderbird Core team) as they become available. There will be separate issues logged for this work.

**Comment by RealRaven2000** [comment]
Latest check-in: Just simplified the code in preparation for dropping the legacy flag:

all shim codes and refer3ences to Postbox / Seamonkey were removed.
minimum version (for testing) is Thunderbird 68.
[smartTemplate-fx-3.0pre6.zip](https://github.com/RealRaven2000/SmartTemplate4/files/4996836/smartTemplate-fx-3.0pre6.zip)

note: this version doesn't install in Thunderbird 78 - a lot more work is necessary.

**Comment by opto** [comment]
so, the next version installs in TB 78, but does not yet do very much except throwing bugs. Still, a lot of conversions to new code are done already.
We started to catch bugs. Will need quite some work, but: quickfolders is already pretty functional in 78, we will get there for smarttemplates as well.

Klaus/opto

**Comment by RealRaven2000** [comment]
I pulled ESR78-opto but manifest has `"strict_max_version": "69.0"` and the` legacy `flag? Are you sure you pushed the latest version of everything?

**Comment by RealRaven2000** [comment]
here is the first early alpha release:

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre27

Expect a more functional version within the next 10 days! please comment below on any issues found with prereleases for Tb78

**Comment by RealRaven2000** [comment]
here is the first early alpha release:

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre27

Expect a more functional version within the next 10 days! please comment below on any issues found with prereleases for Tb78

**Comment by RealRaven2000** [comment]
here is the first early alpha release:

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre27

Expect a more functional version within the next 10 days! please comment below on any issues found with prereleases for Tb78

**Comment by gberkouwer** [comment]
How is it going with the Tb78 version?

**Comment by RealRaven2000** [comment]
> 
> 
> How is it going with the Tb78 version?

We have hit a snag with the completely fucked up preferences system which I am going to repair with John Bieling early next week (i am hoping he has time to assist me on Monday). Once that is sorted I will build a new beta. If you find any major issues in pre27 please append them below in this issue.

Then I can dedicate some of my own time to integration of the external file template menus with the buttons in the header area - unfortunately these were also fucked up by Mozilla in that they removed the "icons only" method. You may have seen that the new dropdown arrows look kind of sad if your toolbar buttons have labels, but they work well when you remove them. 

Mozilla has just broken too many things, we are stomping out the fires currently. Tbh, I was thinking for a long time that I wouldn't be able to fix everything but then I hired external developers and said ok doesn't matter if I go into debt for a while, mu users are more important. I will DEFINITELY have my three main Add-ons (quickFilters, QuickFolders, SmartTemplate4) compatible by the end of October. 

The "freebies" may have to wait a little longer, because they are net losses, _obviously_. (the majority of users still thinks software like this is paid by the tooth fairy)

**Comment by gberkouwer** [comment]
I am not a developer so I cannot help you with that, just a registered user :-). I can just say keep up the good work and thanks in advance!

**Comment by msebald** [comment]
Thank you for the Beta version of SmartTemplates for TB78. I have to following issue:

![image](https://user-images.githubusercontent.com/249907/94415848-64962280-017e-11eb-9d58-f52af2777f8e.png)
![image](https://user-images.githubusercontent.com/249907/94415899-72e43e80-017e-11eb-8a12-d5ee10e5f637.png)

This affects new message, reply and reply-all.

Everything works, but it does not look how it should look.

**Comment by RealRaven2000** [comment]
> 
> 
> Thank you for the Beta version of SmartTemplates for TB78. I have to following issue:
> 
> This affects new message, reply and reply-all.
> 


I am aware of this - at the moment it only works nicely if you configure the toolbar to show in "icon only" mode. Thunderbird Core has broken this thoroughly so I will need to get a few hours of work in to invent a new way to fix this.

**Comment by HamburgerJungeJr** [comment]
I found another little (but annoying= ;) ) issue. 
If I want to provide a template for a single account and not for all accounts, I cannot select the tab for New Email. Instead it shows the tab for replying. Also for replying the tab for forwarding is shown. 

If I select the General account everything works fine. Also I can then switch to a specific account and provide a template for a new email.

**Comment by RealRaven2000** [comment]
> 
> 
> I found another little (but annoying= ;) ) issue.
> If I want to provide a template for a single account and not for all accounts, I cannot select the tab for New Email. Instead it shows the tab for replying. Also for replying the tab for forwarding is shown.
> 
> If I select the General account everything works fine. Also I can then switch to a specific account and provide a template for a new email.

can you check the javascript error console for any clues please? In Windows Ctrl+Shift+J is the fastest way to get there, otherwise the tools menu under web development.

**Comment by HamburgerJungeJr** [comment]
These are the only messages I get when opening the settings.
```SmartTemplate⁴ [logTime init]
getBoolPref(extensions.smartTemplate4.common.newhtml) failed:
Err:[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://smarttemplate4/content/smartTemplate-prefs.js :: getBoolPref :: line 57"  data: no]
SmartTemplate⁴ 15:40:33.756  [0 ms]	 
getBoolPref(extensions.smartTemplate4.common.rsp) failed:
Err:[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://smarttemplate4/content/smartTemplate-prefs.js :: getBoolPref :: line 57"  data: no]
SmartTemplate⁴ 15:40:33.756  [0 ms]	 
getBoolPref(extensions.smartTemplate4.common.fwd) failed:
Err:[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://smarttemplate4/content/smartTemplate-prefs.js :: getBoolPref :: line 57"  data: no]```

**Comment by RealRaven2000** [comment]
I just uploaded a new prerelease, which can be downloaded here:

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre49

This also addresses the previously mentioned problem of inaccessible "New Email" tab, which is handled in issue #86

**Comment by RealRaven2000** [comment]
I just dropped a new beta version, please download from here:

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre56

This finally makes the file template menus available on the reply / forward button on the header bar (above the message preview)

![image](https://user-images.githubusercontent.com/6314674/97121389-c1e9a900-1715-11eb-8f94-18f6830949de.png)

I know, it doesn't look quite perfect (it works better with the Add-on  "Message Header Toolbar Customize", if you then configure the buttons to be "icons only" without text) - but hopefully I will find a way to fix this size issue soon, too. It's not possible to convert the existing buttons to menu toolbar buttons, so I had to add my own versions "underneath" - to make them the exact size of the real buttons is actually more difficult than thought.

**Comment by RealRaven2000** [comment]
Added a new beta version, which repairs broken functionality in the "Write new message" case.

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre57

Since the addressing widgets were completely re-engineered, the part of clicking on the fields had to be rewritten. Still to do: the "change template..." button still looks somewhat wonky.

**Comment by RealRaven2000** [comment]
New beta! Includes 2 PRs from John Bieling who came up with a more compatible version of hacking the forward buttons and turning them into menu dropdown buttons. Should also work if multiple other Add-ons modify these buttons using the same hack.

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre65

**Comment by RealRaven2000** [comment]
Latest beta: Added single message window support and tidied up the code so the Add-on tidies up after itself, too:

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre69

**Comment by reiba** [comment]
SUPER!
Version 65 war für mich DER grosse Sprung. Sieht ja makellos aus!
Frage: oben auf der Toolbar bei "Antworten" oder auch bei "Weiterleiten" (dasselbe auch oberhalb der Mail-vorschauanzeige werden mir nur die Einträge "Smarttemplate-DateiVorlage anzeigen..." sowie "Menü konfigurieren.." angezeigt.
Ist das normal?!? Ich meine mich zu errinnern, dass mir doch auch jeweils meine Datei-Vorlagen angezeigt werden...
Hier zwei Screenshots.
DANKE für die tolle Arbeit!!!!!
![Zwischenablage-2](https://user-images.githubusercontent.com/59339307/98005311-2e893580-1df1-11eb-8cb0-5cbb708dc448.jpg)
![Zwischenablage-1](https://user-images.githubusercontent.com/59339307/98005315-2f21cc00-1df1-11eb-856e-065fc715b812.jpg)

**Comment by RealRaven2000** [comment]
> SUPER!
> Version 65 war für mich DER grosse Sprung. Sieht ja makellos aus!
> Frage: oben auf der Toolbar bei "Antworten" oder auch bei "Weiterleiten" (dasselbe auch oberhalb der Mail-vorschauanzeige) werden mir nur die Einträge "Smarttemplate-DateiVorlage anzeigen..." sowie "Menü konfigurieren.." angezeigt.
> Ist das normal?!? Ich meine mich zu errinnern, dass mir doch auch jeweils meine Datei-Vorlagen angezeigt werden...
> Hier zwei Screenshots.
> DANKE für die tolle Arbeit!!!!!

Has Du schon [version 69](https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre69) ausprobiert?

Auch bitte mal nachsehen ob im Einstellungs Dialog unter Vorlagen / Antworten schon Vorlagen eingetragen sind? Diese werden im Profilverszeichnis "extensions" in der Datei `smartTemplates.json` abgelegt. Der Eintrag _Menü konfigurieren_ kann genutzt werden um direkt in das richtige Panel einzuspringen. Also z. B. vom Antworten _Menü:

![image](https://user-images.githubusercontent.com/6314674/98114093-a5c7d380-1e9c-11eb-8129-432534f2286e.png)

..wird automatisch der Eintrag HTML Vorlagen / Antworten ausgewählt:
![image](https://user-images.githubusercontent.com/6314674/98114190-c859ec80-1e9c-11eb-87f0-4455e2386b7e.png)

wenn da noch nichts steht, mit dem Datei-Picker rechts unten und _Hinzufügen_ neue Einträge erstellen:

![image](https://user-images.githubusercontent.com/6314674/98114340-0525e380-1e9d-11eb-9de5-71fcf558c1df.png)

**Comment by reiba** [comment]
Vielen Dank!
Das war für mich total neu, dass ich auch unter Antworten und unter Weiterleiten die HTML-Vorlagen eintragen müsste.
So deppert ;-)
Wieder was gelernt.
Und ja: Bin immer scharf auf die nächste neueste Preversion von SmartTemplate. Arbeitet für mich und meine Bedürfnisse inzwischen perfekt (nicht nur bzgl. HTML-Vorlagen sondern auch die "anderen" einzufügenden Zeilen.
Vielen Dank

**Comment by RealRaven2000** [comment]
> Vielen Dank!
> Das war für mich total neu, dass ich auch unter Antworten und unter Weiterleiten die HTML-Vorlagen eintragen müsste oder könnte.

Also der Hauptgrund dafür ist auch ziemlich deppert: die Variable `%from%` bezieht sich auf den Original absender der Email.  Beim Schreiben einer neuen wäre das aber der Benutzer selber, und dafür muss man für den Adressaten `%to%` einsetzen. 
Dann wäre also legitimes "antworten" Template-Beispiel:

<p>Lieber %from(firstname)%</p>
<p>%

**Comment by benibela** [comment]
After updating this to the newest version from the thunderbird sites my javascript templates  `%{% (function(){ return "..." })()%}%` do not work anymore. What has happened?

**Comment by RealRaven2000** [comment]
> After updating this to the newest version from the thunderbird sites my javascript templates `%{% (function(){ return "..." })()%}%` do not work anymore. What has happened?

I am not sure, but it is difficult to get them through reviews - they really do not like the existence of evalInSandbox( ), It may even be possible that this function is deprecated. Feel free to create a PR on the [ESR78 branch](https://github.com/RealRaven2000/FiltaQuilla/tree/ESR78) if you would like to fix it.

**Comment by RealRaven2000** [comment]
I am going to close this issue as we have now finalized conversion work - if you find new issues in Thunderbird 78 just simply raise a new issue and I will tag it as Tb78

**Comment by benibela** [comment]
> Just checking: you may want to disable line 2806:
> 
> ```
>   let supportEval = true;
>   // it still works in 68.1.2, not sure when they will deprecate it...
>   if (util.versionGreaterOrEqual(util.AppverFull, "69")) 
>     supportEval = false;
> ```
> 



I just disabled that and then it works

**Comment by RealRaven2000** [comment]
> > Just checking: you may want to disable line 2806:
> > ```
> >   let supportEval = true;
> >   // it still works in 68.1.2, not sure when they will deprecate it...
> >   if (util.versionGreaterOrEqual(util.AppverFull, "69")) 
> >     supportEval = false;
> > ```
> 
> I just disabled that and then it works

Perfect! I will enable for the next release. Hopefully the reviewers will allow it. If not I will put it behind a "hidden setting" in the default preferences.

**Comment by RealRaven2000** [comment]
> > Just checking: you may want to disable line 2806:
> > ```
> >   let supportEval = true;
> >   // it still works in 68.1.2, not sure when they will deprecate it...
> >   if (util.versionGreaterOrEqual(util.AppverFull, "69")) 
> >     supportEval = false;
> > ```
> 
> I just disabled that and then it works

Dear @benibela :

In Release 5.1 I made a (hidden) config setting to enable JavaScript - please set:
`extensions.smartTemplate4.allowScripts = true`

So far no complaints from the reviewers.
