### ISSUE TITLE
Add support for extra header attributes e.g. List-Unsubscribe

### ISSUE THREAD

**Issue by nsolvepaul** [RealRaven2000/SmartTemplate4#71]
http://www.faqs.org/rfcs/rfc2369.html gives:
3.2. List-Unsubscribe

   The List-Unsubscribe field describes the command (preferably using
   mail) to directly unsubscribe the user (removing them from the list).

   Examples:

     List-Unsubscribe: <mailto:list@host.com?subject=unsubscribe>
     List-Unsubscribe: (Use this command to get off the list)
         <mailto:list-manager@host.com?body=unsubscribe%20list>
     List-Unsubscribe: <mailto:list-off@host.com>

     List-Unsubscribe: <http://www.host.com/list.cgi?cmd=unsub&lst=list>,
         <mailto:list-request@host.com?subject=unsubscribe>

Something like:
`%header.set(list-unsubscribe,"<mailto:unsubscribe@nsolve.com?subject=Unsubscribe>")%
`

**Comment by RealRaven2000** [comment]
Thanks for the suggestion - so at the moment the header modifications are highly restricted to a "whitelist" of headers, see the SmartTemplate function `modifyHeader()` :

```
    function modifyHeader(hdr, cmd, argString, matchFunction="") {
      const whiteList = ["subject","to","from","cc","bcc","reply-to","priority"],
            ComposeFields = gMsgCompose.compFields;
```

...and then there is highly specialized code that only allows changing these fields based on text retrieved by the text match function. I guess we could have an experimental advanced option that doesn't restrict this header type and allows access to any header, under the assumption that the user knows what they do and it would have to be a text based header (so, for instance not a date or integer).

In your case we could have to most likely be able to append an entirely new header (especially when writing a new mail and not replying to an existing one that has this header field). So far I hacked the code as well as I could to find the correct fields in composer when writing a new mail, using the global variable `gMsgCompose.compFields` . Now I am currently unsure whether this one supports adding custom header or whether that is something that happens later on (during the send command) so I ned to do quite a bit research for this...

**Comment by nsolvepaul** [comment]
Thank you for the quick and considered reply.  For sure this will help me greatly, having used SmartTemplates4 for one day (with a good few hours configuring and testing it) I feel it will assist me a lot especially with this extra feature - which is essential to  ensure we pass Spam checks

**Comment by RealRaven2000** [comment]
> Thank you for the quick and considered reply. For sure this will help me greatly, having used SmartTemplates4 for one day (with a good few hours configuring and testing it) I feel it will assist me a lot especially with this extra feature - which is essential to ensure we pass Spam checks

Can you try the following test version. I am making an exception for any header starting with the word "list", I also made sure that the case of what you set is preserved:

[smartTemplate-fx-3.4pre20.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5851022/smartTemplate-fx-3.4pre20.zip)

to install, drag the zip file into Thunderbird Add-ons Manager - I used `%header.set(List-Id,"Test List Id")%` with success.

**Comment by RealRaven2000** [comment]
> Thank you for the quick and considered reply. For sure this will help me greatly, having used SmartTemplates4 for one day (with a good few hours configuring and testing it) I feel it will assist me a lot especially with this extra feature - which is essential to ensure we pass Spam checks

Did you get to test the prerelease above by any chance? It would be nice if the change could make it into the next official version of SmartTempaltes (3.4) ... - if you have any other prefixes (apart from "list-") that you think should be supported I am open to suggestions.

**Comment by RealRaven2000** [comment]
Implemented in:

- 3.4 Release for Thunderbird 78 - 05/Feb/2021
- 2.14 Thunderbird 68 - 05/02/2021
