### ISSUE TITLE
From the variables console, clicking the %style()% command erroneously inserts as a %file()% instead

### ISSUE THREAD

**Issue by KonstabelKen** [RealRaven2000/SmartTemplate4#75]
ST4 v2.11.1

**Comment by RealRaven2000** [comment]
Yeah looks like the "copy variable" command does some bad things - it should definitely insert %style(..)% here! 
Thanks for finding this.

Will fix ASAP!

**Comment by RealRaven2000** [comment]
Fixed in 2.11.2 - published 10/07/2020
