### ISSUE TITLE
%file()% path truncated at front by 1 letter on Mac OS

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplate4#77]
The first letter of a  %file()% fileName path is cut off on Mac.

Example: %file(st5.html)% tried to include the file t5.html. Currently the only workaround is to add a "padding" character before the file path name.

**Comment by hauber** [comment]
The problem is in content/smartTemplate-util.js:1408 — It says the first character of `filePath` should be removed if `path` starts with a slash. To my understanding, it should not be the first character of `path` but `filePath` that triggers this.

I created a suggestion for a fix. (It should have changed only 4 lines of code, don't know why Github's differencing shows much more; maybe whitespace.)

**Comment by RealRaven2000** [comment]
Can you send me your merged, complete smartTemplate-util.js? then I can re-merge manually...

**Comment by hauber** [comment]
[smartTemplate-util.js.zip](https://github.com/RealRaven2000/SmartTemplate4/files/4921002/smartTemplate-util.js.zip)

**Comment by RealRaven2000** [comment]
Thank you. I got myself into a complete unmanageable mess after trying to merge the changes, so I will roll back and then merge manually (much easier. damn you github)

**Comment by RealRaven2000** [comment]
I committed the merge now, I think it should be working - can you test it on Mac?

Here is my build:
[smartTemplate-fx-2.12pre2.zip](https://github.com/RealRaven2000/SmartTemplate4/files/4924975/smartTemplate-fx-2.12pre2.zip)

**Comment by hauber** [comment]
First tests with templates worked fine on Mac, will do some more testing. Thanks.

**Comment by RealRaven2000** [comment]
I want to do a backported version for 2.12 for users of the old version - are you still on Thunderbird 68?

**Comment by RealRaven2000** [comment]
Fixed in Releases [2.12.1](https://github.com/RealRaven2000/SmartTemplate4/releases/tag/2.12.1) and [3.1](https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.1)
