### ISSUE TITLE
Add an advanced notice about soon-to-expire license

### ISSUE THREAD

**Issue by goozak** [RealRaven2000/SmartTemplate4#82]
Would be nice to be warned that our license is about to expire.

An email to the licensed address a couple of days in advance would be best, but a banner in the **main** Thunderbird UI would also be good.

While my license was expired, I had the popup/delay when writing a new email and the banner at the bottom of this email.  This location for a renewal notice might not be ideal since people don't necessarily **write** a new email everyday.

**Comment by RealRaven2000** [comment]
definitely! I also want the counter to reset to 0 so there is only the sliding notification and not impact on your workflow.

**Comment by RealRaven2000** [comment]
I was thinking of a sliding notification in the main window, but it does take too much screen estate. Maybe it would be a good idea to add a label to the status bar icon, like this:

![image](https://user-images.githubusercontent.com/6314674/89875836-aad6f880-dbb5-11ea-989b-dbe356bb46f0.png)

If the license was already expired I could make it more prominent with a stronger color:

![image](https://user-images.githubusercontent.com/6314674/89876052-03a69100-dbb6-11ea-856d-5a6b2da9bfd1.png)

clicking the button could then open the SmartTemplate license tab (within settings) automatically:
![image](https://user-images.githubusercontent.com/6314674/89876305-639d3780-dbb6-11ea-8b18-906f137a16e4.png)

**Comment by RealRaven2000** [comment]
I have made some changes so there will be a warning in the status bar if the key expires within 14 days, and then a different one once it has expired.
[smartTemplate-fx-3.4pre25.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5852482/smartTemplate-fx-3.4pre25.zip)

screenshots:
![image](https://user-images.githubusercontent.com/6314674/105420165-cd2a7300-5c37-11eb-97d7-e1eccdca7926.png)
![image](https://user-images.githubusercontent.com/6314674/105420232-e7fce780-5c37-11eb-84a2-ba9014d66190.png)

I hope these will send a strong enough signal for the use to click and look up the License settings. I might force opening the license tab when they open settings once they are in the renewal window.

**Comment by RealRaven2000** [comment]
Implemented in:

- 3.4 Release for Thunderbird 78 - 05/Feb/2021
- 2.14 Release for Thunderbird 68 - 05/02/2021
