### ISSUE TITLE
Dead link on addons homepage

### ISSUE THREAD

**Issue by p91paul** [RealRaven2000/SmartTemplate4#85]
Hi,
the "extension website" link here https://addons.thunderbird.net/thunderbird/addon/smarttemplate4/ (right sidebar) points to the dead location http://smarttemplate4.mozdev.org/

The "support site" links looks correct instead.

**Comment by p91paul** [comment]
Also, on the extension description many links point to http://smarttemplate4.mozdev.org/ which redirects to mozilla homepage

**Comment by RealRaven2000** [comment]
Fixed in 3.0, released on ATN. I need to backport this fix to the Thunderbird 68 version.

**Comment by RealRaven2000** [comment]
Backported in release [2.12.1](https://github.com/RealRaven2000/SmartTemplate4/releases/tag/2.12.1)
