### ISSUE TITLE
Regression: Using %spellcheck% function gives an error message

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplate4#93]
When the function `%spellcheck()%` is used an error is displayed

![image](https://user-images.githubusercontent.com/6314674/98666858-840b9800-2345-11eb-80d2-2b05f5f889bb.png)

this is caused by  the function `GetDictionaryList()` having been refactored in Thunderbird 78.

**Comment by RealRaven2000** [comment]
Ok, here is fixed version for Thunderbird  78. Apart from fixing the regression:
- this also makes the switch %spellcheck(on)% more reliable (it seemed like it was ignored after switching language)

[smartTemplate-fx-3.1pre12.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5517065/smartTemplate-fx-3.1pre12.zip)

to install, drag zip file into Add-ons Manager.

**Comment by PeterMacej** [comment]
The fix works fine but after few hours it gets automatically updated with the official release from the Add-on site.

**Comment by RealRaven2000** [comment]
> The fix works fine but after few hours it gets automatically updated with the official release from the Add-on site.

Sorry I forgot to raise the internal minor version number! Please try this one instead:

[smartTemplate-fx-3.1pre14.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5548726/smartTemplate-fx-3.1pre14.zip)

**Comment by RealRaven2000** [comment]
Fixed in  version 3.1, available since Nov 24 2020 on atn:

https://addons.thunderbird.net/thunderbird/addon/smarttemplate4/versions/?page=1#version-3.1
