### ISSUE TITLE
Addressee Variables Are Not Capitalised Correctly

### ISSUE THREAD

**Issue by beebmaster** [RealRaven2000/SmartTemplate4#99]
I'm not sure if it's a bug, or a feature that I'm not using properly.  When using variables in templates such as %to%, %from% etc., where this also shows and quotes the name associated with the e-mail address, the full name quote is not correctly capitalised.

So if I have "Boris Johnson - PM" as the name in my address book, when using the variable, it would be quoted in the header as "Boris Johnson - pm"; also if for example somebody has me as "BeebMaster" in their address book then when replying, I would be quoted in the header as "Beebmaster".

**Comment by RealRaven2000** [comment]
try to disable General Settings / Capitalize Names

![image](https://user-images.githubusercontent.com/6314674/101791200-2bbde680-3afb-11eb-9280-bfa42e67bbaa.png)

**Comment by beebmaster** [comment]
Oh yes, switching it off works! Thank you so much, I would never have thought of trying that.  In fact I checked it was on several times previously in view of what I thought it meant it was doing!

**Comment by RealRaven2000** [comment]
> Oh yes, switching it off works! Thank you so much, I would never have thought of trying that. In fact I checked it was on several times previously in view of what I thought it meant it was doing!

Well it tries to Capitalize correctly but this is actually quite hard to get right when you do it algorhithmically. It basically turns the string into lowercase (which is good if you reply to  "JOE TURNER <joe@turner.com>" and don't want do shout at the poor guy using `Dear %from(firstname)%` ) and then puts the first word into Caps. But there are some words were it fails or doesn't make sense. It's a tricky one especially when it needs to be language-agnostic.
